### ISSUE TITLE
Current Refactoring Risks / Runtime code dependencies

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-test1#3]
Are there any code dependencies that we can break without getting a compiler error? Asked in another way, are there any runtime dependencies that are not checked by the compiler?

I can seed the conversation:
1. I know we use RMI for some of the delegate stuff, I ran into this while working on sounds. With RMI, any public method of any concrete class may be used. I think we are safe to refactor static methods.

2. There is some XML stuff, I don't know what kind of mapping we have between the XML and objects, but this could be another place where we have dependencies that would not be found by the compiler (an example error here would be to remove a class property, then get a runtime error about some property not being found when parsing an XML doc)

Other than RMI (which is basically a gorilla in the room), I think we only have compile time dependencies on our code. Which would mean it is safe to do anything refactor except change the public interface of methods used in Java RMI.

The intended result of this conversation is to have a discussion to identify things we should watch out for while refactoring. Eventually those items would ideally find their way into the wiki of our "prod" repository rather than the wiki associated with "triplea-test"

**Comment by DanVanAtta** [comment]
The map XMLs have references to java classes. So moving or renaming any of these would be bad, for example:
                <delegate name="tech" javaClass="games.strategy.triplea.delegate.TechnologyDelegate" display="Research Technology"/>

**Comment by gaborbernat** [comment]
some of the IDEs (intelliJ) for instance refactors such references if the class is moved :)

**Comment by ron-murhammer** [comment]
Yeah there is a decent amount of reflection type code related to parsing the map XMLs. So you definitely need to be careful around any delegate related classes.

**Comment by ron-murhammer** [comment]
I would avoid any major refactoring without discussing it first with Veqryn.

**Comment by DanVanAtta** [comment]
No disagreement that IDEs *can* do this, but in some cases they will not do a complete job, or are unaware of some dependencies.

The maps are a good example since the map XML is coming from a file in my home folder. The IDE has no knowledge of that location in my case, so the IDE refactoring a class move will think it got everything when it did not. In this example you would get an error when the tripleA game starts and parses the map XMLs (arguably my dev environment should be set up so the maps come from the map repo, but before we document how to set up a dev environment, I'd like to know about runtime dependencies first).

**Comment by gaborbernat** [comment]
Of course, we should refactor only if agreed beforehand, we see a benefit from it, and with throughout testing.

**Comment by ron-murhammer** [comment]
Exactly and one of the main issues holding back refactoring is the lack of unit tests for a large portion of the code. So its very difficult to test if anything is broken when changes are made.

**Comment by gaborbernat** [comment]
could work by first writing a test, make sure it passes, refactor, change tests to complete, test it manually, write tests for new bugs detected, merge in :) given that this is a long and painful process, we should do it where this would lead to some benefits - improved performance, easier extendability, etcetera. Either way it should start with a feature description, talked over and agreed by the main developers.

**Comment by djensen47** [comment]
You can always (and probably should) fork the repo and then create a branch for experimenting with new ideas.

**Comment by gaborbernat** [comment]
true that, but the developer talk about the feature could be part of an enhancement issue

**Comment by DanVanAtta** [comment]
Not talking about features but simplification, aka refactoring. Specifically some changes will be 100% okay to make so long as the compiler does not complain. Others changes will break stuff even if the compiler says it is okay. When simplifying it is important to know which kind of change you are making - one needs testing, the other does not.

**Comment by DanVanAtta** [comment]
RMI is kinda nasty cause you can have methods that look like they are unused but actually are, we have many methods that are not actually used. There are a lot of code simplifications to make. I'm waiting for the repo to become available to start submitting pull requests with some simplifications.

**Comment by gaborbernat** [comment]
from my point of view, a simplification is also a feature/enhancement. while true it adds no new functionality to the game itself, it does improve the development environment which should be just as important in the long run

**Comment by DanVanAtta** [comment]
Regarding git forks:
If I create a fork of this repo "triplea-test1", and then make changes, and Veqry then delets "triplea-test1" and replaces it with "triplea-prod1", will I have any problems submitting pull requests to "triplea-prod1" even though I'm forked from the non-existent repo "triplea-test1"?

**Comment by gaborbernat** [comment]
it depends on a lot of parameters. if the commit hashes are the same (as the content is the same) in the new repo then you can just simply add the new one as a remote, and push your modifications to that. If it differs you can still add it as a remote and do some kind of rebasing, but that can quickly turn out complicated. You can also create patches and apply that one by one. for the minimizing the risk of conflicts you should probably just wait for the final repo.

**Comment by gaborbernat** [comment]
A fork is essentially just a copy of a repository under a different address. This you can add as a remote to your git repository, and push/merge/rebase between remote and local branches. Read into remotes if you want to understand it more deeply: 
https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

A pull request is just merging the remote branch of the fork, and the original repositories branch in some way.

**Comment by DanVanAtta** [comment]
Looking at the tripleA code, simplifying I think is perhaps the #1 or #2 priority. The complexity and number of smells is up there. There are many changes that are not worth much discussion and I would like this to be something of the discussion of those enhancements. Namely if a change falls in the bucket of "safe to make so long as it compiles" (for example, renaming a method parameter, or a method local variable), then we probably should focus on getting the changes made and reviewing the pull requests.

For stuff that is more substantial, like swapping out RMI for some other remoting technology would certainly deserve a much longer discussion. 

In the middle though I think there is more concern, such as what @ron-murhammer  pointed out with regards to test. Turns out testing is pretty easy - you can launch a dev version, join an online game (and/or observe), and play away for hours testing the whole time. Playing a whole game though is a far cry from a fully comprehensive test suite.

Makes me think on a side note that one functional test suite we can build for sanity checks would be to have two AI's play against each other and check for stack traces.

@ron-murhammer , I don't think there is actually any disagreement, but should be an understanding that code simplification can sometimes be necessary to build new features. Also, there is a large magnitude of code changes that can/should/need to be made as well. The #1 rule of a developer is to not break anything, but part of that is making sure the system is simplified enough that you can sanely add stuff to it and be confident it still works.

**Comment by djensen47** [comment]
What @gaborbernat said is basically the wonderful elegance that is git. A remote (e.g. Github) is litteraly a remote copy of a "local" repo.

**Comment by DanVanAtta** [comment]
+1 w.r.t git, though I was told it is more complex and that git is a distributed repository system. Every local copy and fork is it's own master in a sense. But I wasn't sure how much trouble I would have merging back into a new repository, sounds like it would be a lot and we're waiting for the new repository to be up before forking it.

**Comment by djensen47** [comment]
We should probably come up with a wish list of the refactoring we want to do. 

Processing XML is generally slow especially if using reflection. It would be great if we could represent a game as json or even a binary format. It should compress a lot better and since I'm footing the bill for storing all of those files, any further compression would help.

**Comment by djensen47** [comment]
@DanVanAtta I would just wait until we have the final repo to fork it.

**Comment by DanVanAtta** [comment]
Can that wish list take the form of a pull request so long as the changes are not functionally impactful? :p

On a more serious note, there is a lot of simplification to be done, if we try to list it all out, I would be nervous about that depth or process freezing progress.

But, I do think it would be valuable for us to list out the more important refactoring that need to be done.

**Comment by gaborbernat** [comment]
Another sensible subject regarding refactoring is code formatting, we should have a code format standard all of us can use. I vote for going for the Eclipse one, have a format XML (in Eclipse it's native, in IDE one can use https://plugins.jetbrains.com/plugin/6546). Later on we can add it as a Gradle task (to make it non IDE dependent) by using https://github.com/youribonnaffe/gradle-format-plugin. Any thoughts about this?

**Comment by DanVanAtta** [comment]
code format has been spelled out a bit:
tabs, curly braces on their own line, use "m_" and "s_" for class non-final and static non-final.

Those topics I think should be revisited. There is an eclipse formatter with the project. Is IntelliJ able to use the same one? Is everyone an eclipse user, or is it a mix of IntelliJ and eclipse? In general both IDEs tend to need support by a Java project.

**Comment by gaborbernat** [comment]
beside that there are literally hundred other settings, just look over the Eclipse format options for Java, and yes we should also have a specification for XML given that we have a lot of those too

**Comment by DanVanAtta** [comment]
So the formatter that is the "standard" is checked in. The other settings in it are arbitrary it would appear. On top of that the naming convention is not something that can be enforced with a formatter.

**Comment by djensen47** [comment]
> In general both IDEs tend to need support by a Java project.

Since there is a Community Edition of IntelliJ and I believe the pay version is free for Open Source projects. I see no need to use Eclipse. And I have a single nearly undebatable reason for this: Android. If we every want to create an Android version of TripleA, Google just announced they will no longer support Eclipse. Yes, the desktop _could_ be developed on Eclipse and Android on IntelliJ/Android studio but it would make life easier to standardize on one.

One approach could be to standardize on IntelliJ and have special instructions for Eclipse users.

**Comment by gaborbernat** [comment]
Note that with gradle you can open a project in both Eclipse and IDEA. I see no reason to go for IDEA. I've seen developers preferring Eclipse over IDEA, and even some who are far more efficient in Eclipse than IDEA. So I see no reason to force them, as we can achieve our goal by using both of those.

**Comment by DanVanAtta** [comment]
Yeah, the reasons to support both eclipse and intelliJ are more pragmatic, it's more to not limit the labor pool of who can work on the code (in 5 years I may not respond with this same answer, but today I'd suggest it is the case).

So ideally be IDE agnostic, if not, we should be considering both when it comes to development environment.

**Comment by DanVanAtta** [comment]
@gaborbernat I created a new issue to track the conversation of formatting conventions: https://github.com/triplea-game/triplea-test1/issues/5

**Comment by DanVanAtta** [comment]
I created a wiki page to list out some of the refactoring that could be done: https://github.com/triplea-game/triplea-test1/wiki/refactoring-list, I'll move the wiki page to our new repo when it's ready.

The list probably should give the group a feel that there are *many* refactorings that can be done to this code. But, it's too much for us to talk about each and every item, and a lot of these are just good component design type of issues.

The larger stuff, the more architectural things, like using RMI, I think need conversations. Smaller stuff, like I removed this unused method parameter, I don't think there is any real disagreement that we should just do it and submit it via pull request when that is possible.

**Comment by ron-murhammer** [comment]
Woah. Don't you guys have a day job?

So minor refactoring changes can just be done especially when they are within a single class. When you start changing class names/packages or major architecture changes such as RMI or XML parsing then some sort of conversation needs to occur to come to a consensus on if/how it should be done.

Unit testing needs to become a priority for any changes made whether bug fix, feature, or refactoring. This is especially true for any pieces that contain complex logic. I don't really care about unit testing for the UI or AI for example.

I'll leave the formatting and IDE topics for other threads.

**Comment by gaborbernat** [comment]
@ron-murhammer In Europe it's late night :+1:

**Comment by DanVanAtta** [comment]
Closing, sounds like anything beyond RMI calls or the XML to class mapping stuff, any other non-compile time checked dependencies will come up as a surprise.
