### ISSUE TITLE
Ticket Queues and Triage Process

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-test1#8]
Really 5 questions, but lumping them together. Process question. Decisions made about this will get stuck on a wiki somewhere.

1. What kinds of tickets do we need to track?
`feature requests, bug reports, questions`

2. Can we describe what a full ticket flow would look like from user submitting a bug report or feature request, to it becoming a ticket a developer can pick up and start working on.

3. Which ticket types should be handled by github issues?

4. Which ticket types need to be handled by a different ticketing system?

5. Which additional ticketing systems should we consider using?

**Comment by gaborbernat** [comment]
I would vote for now to keep it Github only, later on if the volume picks up, we can move to JIRA. But for now we should have a single central simple system. I consider Github good for this.

**Comment by DanVanAtta** [comment]
I don't necessarily disagree @gaborbernat , but I intend the scope of the question to be a bit larger. Specifically, tickets and users don't mix very well. In my view we  have two sources of a ticket, developers, or end-users. I think all tickets on github should be authored by developers. I like the plan to migrate to JIRA once the github ticket queues get hard to manage. @gaborbernat , what kind of volume were you thinking for us to need to move to JIRA?

So let me go ahead and answer point number 1
"What kinds of tickets do we need to track?"
- questions
- feature requests
- bug reports

How do end-users submit any of these if only developers author the tickets on github? I think the answer is maybe forum posts, and we create tickets for them. Though maybe I'm off base and we are expecting users to create git hub tickets?

**Comment by djensen47** [comment]
I don't see any reason to not use GitHub issues for everything. This is
still an open source project not a commercially supported product. Why
complicate things with Jira or other external bug/issue trackers?

Do as much as we can on Github with as few external services as possible.

The only external service I see us using is Travis for continuous
integration.

**Comment by djensen47** [comment]
> How do end-users, for example, submit a bug report if only developers author the tickets on github? I think the answer is maybe forum posts, and we create tickets for them. Though maybe I'm off base and we are expecting users to create git hub tickets?

Uh, anybody with a Github account can create an issue on any repo in Github. It's not limited to developers. I've seen companies with a Github repo an only use it for issues, no source code at all.

**Comment by DanVanAtta** [comment]
Thinking about the user base. They have sourceforge forum logins, and at some point stopped using sorce forge tickets. This makes me think they are ticket adverse (which is okay since tickets from end-users tend to lack a lot of necessary details and tend to need more thinking before work can begin).

But bottom line, I think Veqry said somewhere that users don't create tickets (but they clearly still use the forum).

So, github I think for us is not good for end-users maybe, they already don't want to do tickets, and secondly creating yet another login is a barrier that I don't think they'll want to cross.

So my questions are revolving around if we want to have a forum for users to submit stuff, and formalize a process where it gets moved into github issues as a ticket. Part of what I'm wondering as well is how the source forge forum will fit in with github. The forum is actually used, and a migration may not be successful.

**Comment by DanVanAtta** [comment]
Okay, let's keep it simple:
- The forum is used by our users, let's not take that away
- All developer tasks should come from a github ticket (rather than source forge ticket). It does not matter who is the author of the ticket.

For the ticket triage process, I suppose we'll let things happen organically. Would be nice to find a way to avoid a few hundred plus tickets from piling up.

**Comment by gaborbernat** [comment]
I think there isn't a special volume in mind, when Github get's hard to manage make the switch. 

Tickets:
- advertise the gitthub issue system to be used (users can create issues, devs can close them if they think it's not needed). 
- keep forum section. if a user reports an issue, a dev will make an issue out of it, given that the problem can't be solved right there by the dev. (users can also directly create issue on Github if s/he does choose to do so, and has Github acoount)
